server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://eurake-8084.com:8084/eureka/
  instance:
    hostname: eurake-8083.com
    instance-id: eureka-server-8083
spring:
  application:
    name: eureka-server